version: "3"
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:3.8
    volumes:
      - D:\github\rafalpienkowski.github.io\:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      - 8088:4000